mycloud:
  swagger:
    title: 用户项目接口文档标题
    description: 用户项目接口文档描述
  db:
    host: 123.56.223.66
    database: mycloud
    pwd: W@81888188@ym
  sentinel:
    host: localhost
spring:
  cloud:
    nacos:
      config:
        enabled: false