mycloud:
  db:
    host: mysql
    pwd: 123
  eureka:
    host: eureka
    port: 8761

eureka:
  instance:
    #    hostname: localhost  # 主机名
    #    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    leaseRenewalIntervalInSeconds: 30  # 续约间隔时间
    leaseExpirationDurationInSeconds: 90  # 过期时间
  client:
    service-url:
      defaultZone: http://${mycloud.eureka.host}:${mycloud.eureka.port}/eureka/  # Eureka 服务器地址
    enabled: true

logging:
  level:
    org.example: DEBUG  # 设置指定包的日志级别为 DEBUG