
spring:
  rabbitmq:
    host: 123.56.223.66
    port: 5672
    virtual-host: mycloudhost
    username: mycloud
    password: 123
    listener:
      simple:
        #每次只能获取一条消息, 处理完成才能获取下一条消息
        #如果不控制, 默认可能一次分配多条
        prefetch: 1
        acknowledge-mode: auto #消费者处理完成自动发送回执
        retry:
          enabled: true
          initial-interval: 1000ms
          multiplier: 1
          max-attempts: 3
          stateless: true
server:
  port: 8010


  docker run -d \
--name kibana \
-e ELASTICSEARCH_HOSTS=http://es:9200 \
--network=mycloud \
-p 5601:5601 \
  kibana:7.12.1
